#ifndef STATE_H
#define STATE_H

enum EState {
    RANDOM_EXPLORATION = 0,
    AGGRESSIVE_EXPLORATION = 1,
    MOVE_TO_GOAL = 2,
    RESTING  = 3,
    AVOIDING_COLLISION = 4,
    STATE_SIZE,
    CONTROL_LOOP_START = -1,
    MESSAGE_QUEUE_LENGTH = -2
};

#endif // !STATE_H
